// constants.js
const stateOptions = [
  { label: "ANDHRA PRADESH", value: "ANDHRA PRADESH" },
  { label: "ARUNACHAL PRADESH", value: "ARUNACHAL PRADESH" },
  { label: "ASSAM", value: "ASSAM" },
  { label: "BIHAR", value: "BIHAR" },
  { label: "CHHATTISGARH", value: "CHHATTISGARH" },
  { label: "GOA", value: "GOA" },
  { label: "GUJARAT", value: "GUJARAT" },
  { label: "HARYANA", value: "HARYANA" },
  { label: "HIMACHAL PRADESH", value: "HIMACHAL PRADESH" },
  { label: "JHARKHAND", value: "JHARKHAND" },
  { label: "KARNATAKA", value: "KARNATAKA" },
  { label: "KERALA", value: "KERALA" },
  { label: "MADHYA PRADESH", value: "MADHYA PRADESH" },
  { label: "MAHARASHTRA", value: "MAHARASHTRA" },
  { label: "MANIPUR", value: "MANIPUR" },
  { label: "MEGHALAYA", value: "MEGHALAYA" },
  { label: "MIZORAM", value: "MIZORAM" },
  { label: "NAGALAND", value: "NAGALAND" },
  { label: "ODISHA", value: "ODISHA" },
  { label: "PUNJAB", value: "PUNJAB" },
  { label: "RAJASTHAN", value: "RAJASTHAN" },
  { label: "SIKKIM", value: "SIKKIM" },
  { label: "TAMIL NADU", value: "TAMIL NADU" },
  { label: "TELANGANA", value: "TELANGANA" },
  { label: "TRIPURA", value: "TRIPURA" },
  { label: "UTTAR PRADESH", value: "UTTAR PRADESH" },
  { label: "UTTARAKHAND", value: "UTTARAKHAND" },
  { label: "WEST BENGAL", value: "WEST BENGAL" },
];

module.exports = { stateOptions };
